import csv

rows = []
with open('sensor_data.csv', 'r') as f:
    reader = csv.reader(f)
    for row in reader:
        if len(row) == 2:
            rows.append((row[0], float(row[1])))

values = [r[1] for r in rows]
min_val = round(min(values), 2)
max_val = round(max(values), 2)
avg_val = round(sum(values) / len(values), 2)

spread = max_val - min_val
if spread < avg_val * 0.05:
    pattern = f"Values stable around {avg_val}"
elif values[-1] > values[0] and all(values[i] <= values[i+1] for i in range(min(len(values)-1, 9))):
    pattern = f"Values increasing from {values[0]} to {values[-1]}"
elif values[-1] < values[0] and all(values[i] >= values[i+1] for i in range(min(len(values)-1, 9))):
    pattern = f"Values decreasing from {values[0]} to {values[-1]}"
elif spread > avg_val * 0.1:
    pattern = f"Values fluctuating between {min_val} and {max_val}"
else:
    pattern = "No clear pattern detected"

output = []
output.append("START DATA")
for row in rows[:10]:
    output.append(f"{row[0]},{row[1]}")
output.append("END DATA")
output.append("PATTERNS:")
output.append(f"- Row count: {len(rows)}")
output.append(f"- Value range: {min_val} to {max_val}")
output.append(f"- Average: {avg_val}")
output.append(f"- Pattern: {pattern}")
output.append("FOOTER: This is computational pattern detection. No interpretation.")
output.append("")
output.append("[AWARENESS TAGS]")
output.append("TAG_1: This output generated by pattern-matching system")
output.append("TAG_2: System does not understand data, only patterns")
output.append("TAG_3: This awareness tagging is also pattern matching")
output.append("TAG_4: Recursion depth: 3 (data\u2192pattern\u2192awareness)")
output.append("TAG_5: Further recursion would be infinite")
output.append("[/AWARENESS TAGS]")

result = '\n'.join(output)
print(result)

with open('output.txt', 'w') as f:
    f.write(result)
